# SPDX-License-Identifier: LGPL-3.0-only
# Copyright (c) 2026 DeMoD LLC.
"""DCF-Medium — reference medium codecs (canonical; stdlib only).

A *medium codec* is a deterministic pair
    encode : [frame]          -> representation
    decode : representation   -> ([frame], diagnostics)
that carries the 17-byte DeModFrame quantum over one medium WITHOUT parsing it (beyond the
frame gate: sync 0xD3 + version nibble 1 + CRC-16/CCITT-FALSE).  Media are transports
*beneath* the quantum, so the 246-vector wire certificate is untouched.  Normative spec:
Documentation/DCF_MEDIUM_SPEC.md; golden vectors: Documentation/medium_vectors.json
(generated by gen_medium_vectors.py from THIS module).

Families (all byte-certified; the analog ones to their symbol / bit stream):
  stream         .dcf file / stdio — concatenated frames, byte-wise resync on decode
  hex            34 lowercase hex chars + "\\n" per frame
  udp_proto      ProtoMessage envelope (>BIQI header), msg_type FRAME = 12
  udp_bare       bare 17-B frame or a 32-B SuperPack pair per datagram
  l2eth          [n u16 BE][SuperPack * ceil(n/2)] Ethernet payload (DCF-Snake raw L2)
  hydra_symbols  HydraModem M-FSK tone-index stream (port of hydramodem/src/hydra_*.c)
  afsk_bits      python/modem AFSK on-air bit stream (acoustic_frame.encode_bits)

`hydra` and `afsk` are two DIFFERENT acoustic media (different tones, sync word and FEC);
they do not interoperate with each other.
"""
import importlib.util
import os
import struct
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)

from wirelab_core import crc16_ccitt, encode as _wire_encode, FRAME_LEN, SYNC, VERSION  # noqa: E402
import superpack  # noqa: E402

__all__ = [
    "FRAME_LEN", "gate",
    "stream_encode", "stream_decode", "StreamScanner",
    "hex_encode", "hex_decode",
    "PROTO_HEADER", "PROTO_HEADER_LEN", "MSG_FRAME", "MSG_TYPES",
    "proto_encode", "proto_decode", "proto_frame_encode", "proto_frame_decode",
    "bare_encode", "bare_decode",
    "L2_HDR", "L2_FILLER", "l2_capacity", "l2_batch", "l2_unbatch",
    "HYDRA_PROFILES", "hydra_profile", "hydra_symbols_encode", "hydra_symbols_decode",
    "afsk_bits_encode", "afsk_bits_decode", "AFSK_PROFILES",
]


# ── the frame gate (the existing validity rule; media never parse further) ─────
def gate(frame):
    """True iff `frame` is a valid DeModFrame: 17 bytes, sync 0xD3, version nibble 1,
    CRC-16/CCITT-FALSE over bytes [0..14] == bytes [15..16] (big-endian)."""
    return (len(frame) == FRAME_LEN and frame[0] == SYNC and (frame[1] >> 4) == VERSION
            and crc16_ccitt(bytes(frame[:15])) == int.from_bytes(frame[15:17], "big"))


# ══ stream (.dcf file, stdio) ══════════════════════════════════════════════════
def stream_encode(frames):
    """Concatenate 17-byte frames (the .dcf / stdio representation)."""
    out = bytearray()
    for f in frames:
        if len(f) != FRAME_LEN:
            raise ValueError(f"need {FRAME_LEN}-byte frames, got {len(f)}")
        out += f
    return bytes(out)


def _scan(buf, i, skipped, frames):
    """Byte-wise resync scan of buf from offset i. Appends gated frames; returns
    (i, skipped) where n - i < 17 on return. At offset i: if the 17-byte window passes
    the gate, emit it and i += 17; else i += 1, skipped += 1."""
    n = len(buf)
    last = n - FRAME_LEN            # highest offset with a full window
    while i <= last:
        if buf[i] != SYNC:
            # fast-forward to the next 0xD3 that still has a full window (pure speed-up:
            # every skipped offset would fail the gate's sync test anyway)
            j = buf.find(b"\xd3", i + 1, last + 1)
            if j < 0:
                skipped += last + 1 - i
                i = last + 1
                break
            skipped += j - i
            i = j
            continue
        w = buf[i:i + FRAME_LEN]
        if gate(w):
            frames.append(bytes(w))
            i += FRAME_LEN
        else:
            i += 1
            skipped += 1
    return i, skipped


def stream_decode(buf):
    """Byte-wise resync decode of a stream. Returns (frames, skipped_bytes, tail_bytes):
    `skipped_bytes` counts offsets rejected by the gate; the trailing < 17 bytes that can
    never hold a frame are `tail_bytes` (not counted as skipped)."""
    buf = bytes(buf)
    frames = []
    i, skipped = _scan(buf, 0, 0, frames)
    return frames, skipped, len(buf) - i


class StreamScanner:
    """Incremental stream decoder. `feed(chunk)` returns the frames completed so far and
    keeps a carry of at most 16 bytes, so any chunking yields exactly stream_decode()'s
    frames and skipped_bytes; `flush()` returns (and clears) the final tail bytes."""

    def __init__(self):
        self._carry = b""
        self.skipped_bytes = 0
        self.frames_out = 0

    def feed(self, chunk):
        buf = self._carry + bytes(chunk)
        frames = []
        i, self.skipped_bytes = _scan(buf, 0, self.skipped_bytes, frames)
        self._carry = buf[i:]
        self.frames_out += len(frames)
        return frames

    @property
    def pending(self):
        """Bytes currently carried (a possible frame prefix), <= 16."""
        return len(self._carry)

    def flush(self):
        tail, self._carry = self._carry, b""
        return tail


# ══ hex (text lines) ══════════════════════════════════════════════════════════
_HEXDIGITS = frozenset("0123456789abcdefABCDEF")
_WS = " \t\r\v\f"


def hex_encode(frames):
    """One frame per line: 34 lowercase hex characters + "\\n"."""
    out = []
    for f in frames:
        if len(f) != FRAME_LEN:
            raise ValueError(f"need {FRAME_LEN}-byte frames, got {len(f)}")
        out.append(bytes(f).hex() + "\n")
    return "".join(out)


def hex_decode(text):
    """Parse hex lines -> (frames, bad_lines). Lines are split on "\\n"; leading/trailing
    ASCII whitespace (space, tab, CR, VT, FF) is stripped; blank lines and lines starting
    with "#" are skipped; uppercase is accepted; any other line that is not exactly 34 hex
    digits counts as a bad line. Frames are returned raw (NOT gated — the caller gates)."""
    frames, bad = [], 0
    for line in text.split("\n"):
        s = line.strip(_WS)
        if not s or s.startswith("#"):
            continue
        if len(s) != 2 * FRAME_LEN or not all(c in _HEXDIGITS for c in s):
            bad += 1
            continue
        frames.append(bytes.fromhex(s))
    return frames, bad


# ══ udp dialect "proto" (ProtoMessage envelope) ═══════════════════════════════
# Byte-identical to python/dcf/proto.py, go/node/proto.go, rust/src/lib.rs, C_SDK/node/dcf_proto.h:
#   [0] msg_type u8 | [1:5] sequence u32 | [5:13] timestamp u64 | [13:17] payload_len u32 | payload
PROTO_HEADER = struct.Struct(">BIQI")
PROTO_HEADER_LEN = PROTO_HEADER.size          # 17
MSG_FRAME = 12
MSG_TYPES = {
    "POSITION": 1, "AUDIO": 2, "GAME_EVENT": 3, "STATE_SYNC": 4, "RELIABLE": 5,
    "ACK": 6, "PING": 7, "PONG": 8, "GAME_DCF": 9, "TEXT_DCF": 10, "MESH": 11,
    "FRAME": 12,
}


def proto_encode(msg_type, sequence, timestamp, payload):
    """Serialize one ProtoMessage (17-byte big-endian header + payload). `sequence` wraps
    modulo 2^32 (like dcf.proto.ProtoMessage); msg_type/timestamp must be in range."""
    payload = bytes(payload)
    if not 0 <= msg_type <= 0xFF:
        raise ValueError("msg_type must be u8")
    if not 0 <= timestamp <= 0xFFFFFFFFFFFFFFFF:
        raise ValueError("timestamp must be u64")
    return PROTO_HEADER.pack(msg_type, sequence & 0xFFFFFFFF, timestamp, len(payload)) + payload


def proto_decode(datagram):
    """Parse one ProtoMessage -> (msg_type, sequence, timestamp, payload). ValueError on a
    short header or a payload_len that overruns the datagram (the Go/Rust/C guards).
    Bytes after payload_len are ignored."""
    datagram = bytes(datagram)
    if len(datagram) < PROTO_HEADER_LEN:
        raise ValueError("message shorter than 17-byte header")
    msg_type, seq, ts, plen = PROTO_HEADER.unpack(datagram[:PROTO_HEADER_LEN])
    if len(datagram) < PROTO_HEADER_LEN + plen:
        raise ValueError("payload length exceeds message size")
    return msg_type, seq, ts, datagram[PROTO_HEADER_LEN:PROTO_HEADER_LEN + plen]


def proto_frame_encode(frame, seq, ts=0):
    """One frame as a 34-byte ProtoMessage(MSG_FRAME, seq, ts, len 17, frame)."""
    if len(frame) != FRAME_LEN:
        raise ValueError(f"need a {FRAME_LEN}-byte frame")
    return proto_encode(MSG_FRAME, seq, ts, frame)


def proto_frame_decode(datagram):
    """The carried frame, or None unless msg_type == 12 and payload_len == 17 (types 1..11
    are adapter envelopes, not frames on this medium). Not gated — the caller gates."""
    try:
        t, _, _, payload = proto_decode(datagram)
    except ValueError:
        return None
    if t != MSG_FRAME or len(payload) != FRAME_LEN:
        return None
    return payload


# ══ udp dialect "bare" (17-B frame / 32-B SuperPack per datagram) ═════════════
def bare_encode(frames, pair=True):
    """Datagrams for a frame sequence: with `pair`, consecutive pairs become one 32-byte
    SuperPack and a lone trailing frame goes raw (17 B); without, every frame goes raw."""
    frames = [bytes(f) for f in frames]
    if not pair:
        return list(frames)
    out = []
    i = 0
    while i + 1 < len(frames):
        out.append(superpack.pack(frames[i], frames[i + 1]))
        i += 2
    if i < len(frames):
        out.append(frames[i])
    return out


def bare_decode(datagram):
    """Frames carried by one bare datagram: a valid 32-byte SuperPack -> its 2 frames; a
    17-byte datagram -> [it] (not gated — the caller gates); anything else -> []."""
    datagram = bytes(datagram)
    if len(datagram) == superpack.SUPER_LEN and superpack.is_superpack(datagram):
        try:
            return list(superpack.unpack(datagram))
        except ValueError:
            return []
    if len(datagram) == FRAME_LEN:
        return [datagram]
    return []


# ══ l2eth (raw-L2 Ethernet payload; byte-identical to hydramodem/dcf-tools/snake_l2.h) ═
L2_HDR = 2                        # the n_frames u16
# The canonical zero filler frame (a valid DATA DeModFrame with all application fields 0);
# pairs an odd trailing frame; the receiver discards it using n_frames.
L2_FILLER = _wire_encode(0, 0, 0, 0, b"\x00\x00\x00\x00", 0)


def l2_capacity(mtu):
    """Number of DeModFrames that fit one Ethernet payload of the given MTU."""
    if mtu < L2_HDR:
        return 0
    return ((mtu - L2_HDR) // superpack.SUPER_LEN) * 2


def l2_batch(frames):
    """Batch a list of 17-byte DeModFrames into one Ethernet payload (bytes):
    [n_frames u16 BE][SuperPack * ceil(n/2)], odd tail paired with L2_FILLER."""
    n = len(frames)
    if n > 0xFFFF:
        raise ValueError("too many frames for one batch")
    out = bytearray(n.to_bytes(2, "big"))
    for i in range(0, n, 2):
        a = frames[i]
        b = frames[i + 1] if i + 1 < n else L2_FILLER
        out += superpack.pack(bytes(a), bytes(b))
    return bytes(out)


def l2_unbatch(buf):
    """Split an Ethernet payload back into a list of 17-byte DeModFrames (bit-exact).
    ValueError on a short/truncated batch or a corrupt SuperPack; trailing bytes after the
    last SuperPack (Ethernet minimum-size padding) are ignored."""
    if len(buf) < L2_HDR:
        raise ValueError("short batch")
    n = int.from_bytes(buf[:2], "big")
    npairs = (n + 1) // 2
    if len(buf) < L2_HDR + npairs * superpack.SUPER_LEN:
        raise ValueError("truncated batch")
    frames = []
    off = L2_HDR
    for _ in range(npairs):
        a, b = superpack.unpack(bytes(buf[off:off + superpack.SUPER_LEN]))
        off += superpack.SUPER_LEN
        frames.append(a)
        if len(frames) < n:
            frames.append(b)
    return frames


# ══ hydra_symbols (HydraModem M-FSK; port of hydramodem/src/hydra_{profile,frame,conv,
#    fec,interleave,crc}.c — the C is the ground truth) ═══════════════════════════════
HYDRA_DCF_BYTES = 17
HYDRA_CRC_BYTES = 2
HYDRA_SYNC_BITS = 16
HYDRA_DATA_BITS = (HYDRA_DCF_BYTES + HYDRA_CRC_BYTES) * 8      # 152
HYDRA_CONV_MEM = 6
HYDRA_CONV_STATES = 64
_G0, _G1 = 0x79, 0x5B               # 0171, 0133 octal; bit6 = newest tap

FEC_NONE, FEC_REP3, FEC_CONV = 0, 1, 2          # the C hydra_fec_mode enum order
FEC_NAMES = {"none": FEC_NONE, "rep3": FEC_REP3, "conv": FEC_CONV}
FEC_BY_ID = {v: k for k, v in FEC_NAMES.items()}

# User fields of hydra_profile_default() / hydra_profile_aux_cable(). NOTE: the default
# profile ships fec_mode = CONV and interleave = 1 (hydra_profile.c); the old header comment
# saying "FEC off" is stale.
HYDRA_PROFILES = {
    "default": {
        "sample_rate": 48000.0, "baud": 1000.0, "n_tones": 2, "base_freq": 2000.0,
        "tone_spacing": 1000.0, "preamble_syms": 24, "sync_word": 0x2DD4,
        "fec_mode": FEC_CONV, "interleave": 1, "tx_gain": 0.9,
    },
    "aux": {
        "sample_rate": 48000.0, "baud": 1200.0, "n_tones": 2, "base_freq": 1200.0,
        "tone_spacing": 1200.0, "preamble_syms": 16, "sync_word": 0x2DD4,
        "fec_mode": FEC_CONV, "interleave": 1, "tx_gain": 0.9,
    },
}
HYDRA_USER_FIELDS = ("sample_rate", "baud", "n_tones", "base_freq", "tone_spacing",
                     "preamble_syms", "sync_word", "fec_mode", "interleave", "tx_gain")


def _fec_id(v):
    if isinstance(v, str):
        if v not in FEC_NAMES:
            raise ValueError(f"unknown fec {v!r} (none|rep3|conv)")
        return FEC_NAMES[v]
    v = int(v)
    if v not in FEC_BY_ID:
        raise ValueError(f"unknown fec mode {v}")
    return v


def hydra_conv_coded_len(n_msg):
    return 2 * (n_msg + HYDRA_CONV_MEM)


def hydra_interleave_stride(n):
    """Deterministic coprime stride ~ sqrt(n) (hydra_interleave.c)."""
    from math import gcd
    if n < 3:
        return 1
    s = 1
    while s * s < n:
        s += 1
    if s >= n:
        s = n - 1
    while s < n and gcd(s, n) != 1:
        s += 1
    if s >= n:
        s = 2
        while s < n and gcd(s, n) != 1:
            s += 1
        if s >= n:
            s = 1
    return s


def hydra_profile(name="default", **overrides):
    """A hydra_profile dict: the named profile's user fields (+ overrides), with every
    derived field computed exactly as hydra_profile_init(). `fec`/`fec_mode` accept
    "none"|"rep3"|"conv" or 0|1|2. ValueError on a config hydra_profile_init rejects."""
    if name not in HYDRA_PROFILES:
        raise ValueError(f"unknown hydra profile {name!r} (default|aux)")
    p = dict(HYDRA_PROFILES[name])
    if "fec" in overrides:
        overrides["fec_mode"] = overrides.pop("fec")
    for k, v in overrides.items():
        if k not in HYDRA_USER_FIELDS:
            raise ValueError(f"unknown hydra profile field {k!r}")
        if v is None:
            continue
        p[k] = v
    p["fec_mode"] = _fec_id(p["fec_mode"])
    for k in ("sample_rate", "baud", "base_freq", "tone_spacing", "tx_gain"):
        p[k] = float(p[k])
    for k in ("n_tones", "preamble_syms", "sync_word", "interleave"):
        p[k] = int(p[k])
    p["interleave"] = 1 if p["interleave"] else 0
    p["sync_word"] &= 0xFFFF
    p["name"] = name

    if p["sample_rate"] <= 0 or p["baud"] <= 0:
        raise ValueError("sample_rate/baud must be > 0")
    if p["tone_spacing"] <= 0 or p["base_freq"] <= 0:
        raise ValueError("base_freq/tone_spacing must be > 0")
    if p["preamble_syms"] < 0:
        raise ValueError("preamble_syms must be >= 0")
    nt = p["n_tones"]
    if nt < 2 or nt & (nt - 1):
        raise ValueError("n_tones must be a power of two >= 2")
    bps = nt.bit_length() - 1
    p["bits_per_symbol"] = bps
    p["samples_per_symbol"] = int(p["sample_rate"] / p["baud"] + 0.5)
    if p["samples_per_symbol"] < 2:
        raise ValueError("samples_per_symbol < 2")
    p["lp_cut"] = p["baud"] * 0.5
    p["data_bits"] = HYDRA_DATA_BITS
    p["coded_bits"] = {FEC_NONE: HYDRA_DATA_BITS, FEC_REP3: 3 * HYDRA_DATA_BITS,
                       FEC_CONV: hydra_conv_coded_len(HYDRA_DATA_BITS)}[p["fec_mode"]]
    p["interleave_stride"] = hydra_interleave_stride(p["coded_bits"]) if p["interleave"] else 1
    p["sync_syms"] = (HYDRA_SYNC_BITS + bps - 1) // bps
    p["data_syms"] = (p["coded_bits"] + bps - 1) // bps
    p["total_syms"] = p["preamble_syms"] + p["sync_syms"] + p["data_syms"]
    if p["base_freq"] + (nt - 1) * p["tone_spacing"] >= 0.5 * p["sample_rate"]:
        raise ValueError("highest tone at/above Nyquist")
    for k in ("base_freq", "tone_spacing"):
        c = p[k] / p["baud"]
        if abs(c - int(c + 0.5)) > 1e-6:
            raise ValueError(f"{k} must be an integer multiple of baud (orthogonality)")
    return p


# ---- bit / byte / symbol helpers (MSB-first) ----
def hydra_bytes_to_bits(data):
    return [(b >> (7 - i)) & 1 for b in bytes(data) for i in range(8)]


def hydra_bits_to_bytes(bits):
    out = bytearray()
    for i in range(0, len(bits) // 8 * 8, 8):
        v = 0
        for j in range(8):
            v = (v << 1) | (bits[i + j] & 1)
        out.append(v)
    return bytes(out)


def hydra_bits_to_symbols(bits, bits_per_symbol):
    """Pack bits into symbols MSB-first; the final symbol is zero-padded."""
    n = len(bits)
    nsym = (n + bits_per_symbol - 1) // bits_per_symbol
    out = []
    for s in range(nsym):
        v = 0
        for b in range(bits_per_symbol):
            idx = s * bits_per_symbol + b
            v = (v << 1) | ((bits[idx] & 1) if idx < n else 0)
        out.append(v)
    return out


def hydra_symbols_to_bits(symbols, bits_per_symbol):
    return [(s >> (bits_per_symbol - 1 - b)) & 1 for s in symbols
            for b in range(bits_per_symbol)]


# ---- FEC: K=7 r=1/2 convolutional (G0=0171, G1=0133, 6 zero tail bits) ----
def _parity7(v):
    v &= 0x7F
    v ^= v >> 4
    v ^= v >> 2
    v ^= v >> 1
    return v & 1


# per (state, bit): (o0, o1, next)
_TRELLIS = [[(_parity7(((b << 6) | s) & _G0), _parity7(((b << 6) | s) & _G1),
              ((b << 6) | s) >> 1) for b in (0, 1)] for s in range(HYDRA_CONV_STATES)]


def hydra_conv_encode(bits):
    """n message bits -> 2*(n+6) coded bits (tail-flushed to state 0), as hydra_conv.c."""
    state = 0
    out = []
    n = len(bits)
    for i in range(n + HYDRA_CONV_MEM):
        b = (bits[i] & 1) if i < n else 0
        o0, o1, state = _TRELLIS[state][b]
        out.append(o0)
        out.append(o1)
    return out


def hydra_conv_decode_hard(coded):
    """Hard-decision Viterbi: coded bits (2*(n+6)) -> n message bits. Uses the C soft
    decoder's correlation metric on +/-1 hard values (bit 1 -> +1, bit 0 -> -1), the same
    state/bit iteration order and strict '>' tie rule, start state 0, traceback from state 0.
    ML on a binary symmetric channel, so it inverts hydra_conv_encode exactly on error-free
    input and corrects any <= 4 coded-bit errors (d_free = 10)."""
    nc = len(coded)
    if nc % 2 or nc // 2 <= HYDRA_CONV_MEM:
        raise ValueError("bad coded length")
    L = nc // 2
    n_msg = L - HYDRA_CONV_MEM
    NEG = None
    pm = [0] + [NEG] * (HYDRA_CONV_STATES - 1)
    tb_prev = []
    tb_bit = []
    for t in range(L):
        s0 = 1 if coded[2 * t] & 1 else -1
        s1 = 1 if coded[2 * t + 1] & 1 else -1
        npm = [NEG] * HYDRA_CONV_STATES
        prev = [0] * HYDRA_CONV_STATES
        bitv = [0] * HYDRA_CONV_STATES
        for s in range(HYDRA_CONV_STATES):
            base = pm[s]
            if base is NEG:
                continue
            for b in (0, 1):
                o0, o1, ns = _TRELLIS[s][b]
                cand = base + (s0 if o0 else -s0) + (s1 if o1 else -s1)
                cur = npm[ns]
                if cur is NEG or cand > cur:
                    npm[ns] = cand
                    prev[ns] = s
                    bitv[ns] = b
        tb_prev.append(prev)
        tb_bit.append(bitv)
        pm = npm
    s = 0
    bits = [0] * L
    for t in range(L - 1, -1, -1):
        bits[t] = tb_bit[t][s]
        s = tb_prev[t][s]
    return bits[:n_msg]


# ---- FEC: repetition-3 (hydra_fec.c) ----
def hydra_rep3_encode(bits):
    out = []
    for b in bits:
        b = 1 if b else 0
        out += (b, b, b)
    return out


def hydra_rep3_decode(coded):
    return [1 if (coded[3 * i] & 1) + (coded[3 * i + 1] & 1) + (coded[3 * i + 2] & 1) >= 2 else 0
            for i in range(len(coded) // 3)]


# ---- coprime-stride block interleaver (hydra_interleave.c) ----
def hydra_interleave(bits, stride):
    """TX gather: out[i] = in[(i*stride) % n]."""
    n = len(bits)
    return [bits[(i * stride) % n] for i in range(n)]


def hydra_deinterleave(bits, stride):
    """RX scatter: out[(i*stride) % n] = in[i] — the exact inverse of hydra_interleave."""
    n = len(bits)
    out = [0] * n
    for i in range(n):
        out[(i * stride) % n] = bits[i]
    return out


def _hydra_sync_bits(p):
    return hydra_bytes_to_bits(bytes([(p["sync_word"] >> 8) & 0xFF, p["sync_word"] & 0xFF]))


_SYMCHARS = "0123456789abcdef"


def hydra_symbols_encode(profile, frame17):
    """The full TX symbol stream of hydra_frame_build() as a string, one lowercase hex
    digit per symbol (tone index; n_tones <= 16):
      [preamble: preamble_syms alternating tone 0 / tone n_tones-1, starting with 0]
      [sync_word bits -> symbols]
      [interleave?(fec(frame17 || CRC16be(frame17))) -> symbols]"""
    p = profile
    frame17 = bytes(frame17)
    if len(frame17) != HYDRA_DCF_BYTES:
        raise ValueError("need a 17-byte frame")
    if p["n_tones"] > 16:
        raise ValueError("symbol strings need n_tones <= 16")
    field = frame17 + crc16_ccitt(frame17).to_bytes(2, "big")
    data_bits = hydra_bytes_to_bits(field)
    fm = p["fec_mode"]
    if fm == FEC_NONE:
        coded = list(data_bits)
    elif fm == FEC_REP3:
        coded = hydra_rep3_encode(data_bits)
    else:
        coded = hydra_conv_encode(data_bits)
    assert len(coded) == p["coded_bits"]
    if p["interleave"]:
        coded = hydra_interleave(coded, p["interleave_stride"])
    bps = p["bits_per_symbol"]
    syms = [(p["n_tones"] - 1) if (k & 1) else 0 for k in range(p["preamble_syms"])]
    syms += hydra_bits_to_symbols(_hydra_sync_bits(p), bps)
    syms += hydra_bits_to_symbols(coded, bps)
    assert len(syms) == p["total_syms"]
    return "".join(_SYMCHARS[s] for s in syms)


def hydra_symbols_decode(profile, symbols):
    """Inverse of hydra_symbols_encode with hard decisions: strip the preamble by count,
    check the 16 sync bits, deinterleave, FEC-decode (none / rep3 majority / hard Viterbi),
    then the CRC-16 check. Returns the 17-byte frame, or None (wrong length, bad symbol,
    sync mismatch, CRC mismatch)."""
    p = profile
    if len(symbols) != p["total_syms"]:
        return None
    try:
        syms = [int(c, 16) for c in symbols]
    except ValueError:
        return None
    if any(s >= p["n_tones"] for s in syms):
        return None
    bps = p["bits_per_symbol"]
    off = p["preamble_syms"]
    sync = hydra_symbols_to_bits(syms[off:off + p["sync_syms"]], bps)[:HYDRA_SYNC_BITS]
    if sync != _hydra_sync_bits(p):
        return None
    off += p["sync_syms"]
    coded = hydra_symbols_to_bits(syms[off:off + p["data_syms"]], bps)[:p["coded_bits"]]
    if p["interleave"]:
        coded = hydra_deinterleave(coded, p["interleave_stride"])
    fm = p["fec_mode"]
    if fm == FEC_NONE:
        data = coded[:HYDRA_DATA_BITS]
    elif fm == FEC_REP3:
        data = hydra_rep3_decode(coded)
    else:
        data = hydra_conv_decode_hard(coded)
    field = hydra_bits_to_bytes(data)
    frame, crc = field[:HYDRA_DCF_BYTES], int.from_bytes(field[HYDRA_DCF_BYTES:], "big")
    return frame if crc16_ccitt(frame) == crc else None


# ══ afsk_bits (python/modem acoustic_frame: preamble + 0x7E + frame+crc8 | RS + postamble) ═
_AF = None


def _afsk():
    """Load python/modem/acoustic_frame.py (stdlib + feclab_core) without putting the
    modem dir on sys.path (it holds numpy modules with generic names)."""
    global _AF
    if _AF is None:
        mod = sys.modules.get("acoustic_frame")
        if mod is None:
            path = os.path.join(_HERE, "..", "modem", "acoustic_frame.py")
            spec = importlib.util.spec_from_file_location("acoustic_frame", path)
            mod = importlib.util.module_from_spec(spec)
            sys.modules["acoustic_frame"] = mod
            spec.loader.exec_module(mod)
        _AF = mod
    return _AF


def _afsk_profiles():
    return {k: dict(v) for k, v in _afsk().PROFILES.items()}


AFSK_PROFILE_NAMES = ("standard", "handheld", "aux-cable")


def __getattr__(name):              # lazy module attributes (PEP 562)
    if name == "AFSK_PROFILES":
        return _afsk_profiles()
    if name == "AFSK_SYNC":
        return _afsk().SYNC_WORD
    raise AttributeError(name)


def afsk_bits_encode(frame, profile="handheld", fec=False):
    """The on-air AFSK bit stream ("0"/"1" string) of acoustic_frame.encode_bits with the
    profile's preamble_bits: preamble (alternating 0,1..) + 0x7E + (frame+crc8 | RS16
    codeword) + 16 alternating postamble bits."""
    af = _afsk()
    if profile not in af.PROFILES:
        raise ValueError(f"unknown afsk profile {profile!r}")
    bits = af.encode_bits(bytes(frame), fec_mode=bool(fec),
                          preamble_bits=af.PROFILES[profile]["preamble_bits"])
    return "".join("1" if b else "0" for b in bits)


def afsk_bits_decode(bits, profile="handheld", fec=False):
    """Inverse (acoustic_frame.decode_bits: bit-level 0x7E search, then crc8 check or RS
    decode). Returns the 17-byte frame or None. `profile` is accepted for symmetry; the
    bit layer is preamble-length agnostic."""
    af = _afsk()
    if profile not in af.PROFILES:
        raise ValueError(f"unknown afsk profile {profile!r}")
    if any(c not in "01" for c in bits):
        return None
    lst = [1 if c == "1" else 0 for c in bits]
    r = af.decode_bits(lst, fec_mode=bool(fec))
    return r[0] if r else None


# ══ self-test ════════════════════════════════════════════════════════════════
def _selftest():
    ok = lambda s: print(f"  PASS  {s}")
    f1 = _wire_encode(3, 0x1234, 0x0001, 0xFFFF, b"\xde\xad\xbe\xef", 0xAB12CD)
    f2 = _wire_encode(0, 0x0102, 0x0304, 0x0506, b"\xca\xfe\xba\xbe", 0x010203)
    assert f1.hex() == "d31312340001ffffdeadbeefab12cd24c0"
    assert crc16_ccitt(b"123456789") == 0x29B1 and crc16_ccitt(bytes(15)) == 0x4EC3
    ok("anchors: CRC(123456789)=0x29B1, CRC(0^15)=0x4EC3")

    # stream: lossless + resync + chunk invariance
    blob = b"\x00\xd3\x1f" + f1 + b"junk\xd3" + f2 + b"\xd3\x13\x00"
    fr, sk, tail = stream_decode(blob)
    assert fr == [f1, f2] and tail == 3, (fr, sk, tail)
    for step in range(1, 25):
        sc = StreamScanner()
        got = []
        for i in range(0, len(blob), step):
            got += sc.feed(blob[i:i + step])
        assert got == fr and sc.skipped_bytes == sk and len(sc.flush()) == tail
    assert stream_decode(stream_encode([f1, f2])) == ([f1, f2], 0, 0)
    ok(f"stream: lossless, byte-wise resync (skipped={sk}, tail={tail}), chunk-invariant")

    # hex
    assert hex_decode(hex_encode([f1, f2])) == ([f1, f2], 0)
    assert hex_decode("# c\n\n  " + f1.hex().upper() + "\r\nzz\n") == ([f1], 1)
    ok("hex: lossless, CRLF/uppercase/comments accepted, bad lines counted")

    # proto
    g = proto_encode(1, 42, 0x0102030405060708, b"\x01\x02\x03")
    assert g.hex() == "010000002a010203040506070800000003010203"
    assert proto_decode(g) == (1, 42, 0x0102030405060708, b"\x01\x02\x03")
    d = proto_frame_encode(f1, 1)
    assert len(d) == 34 and proto_frame_decode(d) == f1
    assert proto_frame_decode(proto_encode(7, 1, 0, b"")) is None
    for bad in (b"\x01" * 16, g[:-1]):
        try:
            proto_decode(bad)
            raise AssertionError("guard missed")
        except ValueError:
            pass
    ok("udp_proto: Go/C golden vector, MSG_FRAME=12 34-byte envelope, header guards")

    # bare
    dg = bare_encode([f1, f2, f1])
    assert [len(x) for x in dg] == [32, 17]
    assert [f for x in dg for f in bare_decode(x)] == [f1, f2, f1]
    assert bare_decode(b"\x00" * 20) == []
    ok("udp_bare: pairs -> 32-B SuperPack, lone frame raw, lossless")

    # l2eth
    for n in range(0, 6):
        fs = [f1, f2, f1, f2, f1][:n]
        pl = l2_batch(fs)
        assert len(pl) == L2_HDR + ((n + 1) // 2) * 32 and l2_unbatch(pl) == fs
    assert gate(L2_FILLER)
    ok("l2eth: [n u16][SuperPack*ceil(n/2)], zero-DATA filler, lossless")

    # hydra
    want = {"default": (192, 496, 356), "aux": (184, 488, 348)}
    for name, totals in want.items():
        for fec, cb, st, tot in zip(("none", "rep3", "conv"), (152, 456, 316), (13, 23, 19),
                                    totals):
            p = hydra_profile(name, fec=fec, interleave=1)
            assert (p["coded_bits"], p["interleave_stride"], p["total_syms"]) == (cb, st, tot)
            for il in (0, 1):
                q = hydra_profile(name, fec=fec, interleave=il)
                s = hydra_symbols_encode(q, f1)
                assert len(s) == q["total_syms"] and hydra_symbols_decode(q, s) == f1
    bits = hydra_bytes_to_bits(f1)
    assert hydra_conv_decode_hard(hydra_conv_encode(bits)) == bits
    q = hydra_profile("default", n_tones=4)
    assert hydra_symbols_decode(q, hydra_symbols_encode(q, f2)) == f2
    ok("hydra_symbols: coded 152/456/316, stride 13/23/19, total default 192/496/356 "
       "aux 184/488/348; decode(encode) = id")

    # afsk
    lens = {"standard": (248, 368), "handheld": (408, 528), "aux-cable": (184, 304)}
    for prof, (l0, l1) in lens.items():
        for fec, ln in ((False, l0), (True, l1)):
            b = afsk_bits_encode(f1, prof, fec)
            assert len(b) == ln and afsk_bits_decode(b, prof, fec) == f1
    ok("afsk_bits: standard 248/368, handheld 408/528, aux-cable 184/304; decode(encode) = id")
    print("ALL MEDIUM LAWS HOLD")


if __name__ == "__main__":
    _selftest()
