/* test_qkd_certify.c — C certification for the DCF-QKD key-ID beacon L2 framing.
 *
 * Certifies the C implementation (codec/demod_qkd.h) against the cross-language
 * golden vectors (codec/qkd_vectors.gen.h, generated by gen_qkd_vectors.py).
 * Compiled L2-only: no runtime needed for the byte layout.
 *
 * No key material appears here or on the wire — the beacon carries only the key_ID,
 * a non-secret 128-bit identifier.  See Documentation/DCF_QKD_SPEC.md.
 *
 * Build: gcc -std=c11 -Wall -Wextra -I codec -o test_qkd_certify \
 *            C_SDK/tests/test_qkd_certify.c -lm
 */
#include <stdio.h>
#include <string.h>
#include "demod_qkd.h"
#include "qkd_vectors.gen.h"

static int failures = 0;

static void fail(const char *what, int idx) {
    fprintf(stderr, "FAIL: %s [case %d]\n", what, idx);
    failures++;
}

int main(void) {
    /* ── 1. Framing: packetize matches expected frames byte-for-byte ── */
    for (int i = 0; i < QV_N_FRAMING; i++) {
        const qv_framing_t *c = &QV_FRAMING[i];
        uint8_t frames[DCF_QKD_FRAGS][DCF_FRAME_SIZE];
        size_t n = 0;
        if (!dcf_qkd_packetize(c->key_id, c->epoch, c->ts_us, c->src, c->dst,
                               frames, DCF_QKD_FRAGS, &n)) {
            fail("packetize returned false", i);
            continue;
        }
        if (n != c->n_frames || n != DCF_QKD_FRAGS) {
            fail("frame count mismatch", i);
            continue;
        }
        for (size_t f = 0; f < n; f++)
            if (memcmp(frames[f], c->frames[f], DCF_FRAME_SIZE) != 0)
                fail("frame bytes mismatch", i);
    }
    printf("PASS: %d framing cases packetize byte-identically (4 frames each)\n",
           QV_N_FRAMING);

    /* ── 2. Reassembly: reorder / drop→lost / duplicate / interleave / dst filter ── */
    for (int i = 0; i < QV_N_REASM; i++) {
        const qv_reasm_t *c = &QV_REASM[i];
        dcf_qkd_reasm_t r;
        dcf_qkd_reasm_init(&r, c->accept_dst);
        int got = 0, ok = 1;
        for (int f = 0; f < c->n_in; f++) {
            dcf_qkd_key_t out;
            if (dcf_qkd_reasm_push(&r, c->in_frames[f], &out) == DCF_QKD_REASM_KEY) {
                if (got >= c->n_key) { ok = 0; break; }
                const qv_key_t *e = &c->keys[got++];
                if (out.epoch != e->epoch || out.ts_us != e->ts_us ||
                    out.src != e->src || out.dst != e->dst ||
                    memcmp(out.key_id, e->key_id, DCF_QKD_KEY_ID_BYTES) != 0) ok = 0;
            }
        }
        if (got != c->n_key) ok = 0;
        dcf_qkd_lost_t lost[8];
        size_t nlost = dcf_qkd_reasm_finalize(&r, lost, 8);
        if ((int)nlost != c->n_lost) ok = 0;
        for (int l = 0; l < c->n_lost; l++)
            if (lost[l].epoch != c->lost[l].epoch || lost[l].src != c->lost[l].src ||
                lost[l].dst != c->lost[l].dst) ok = 0;
        if (!ok) fail(c->name, i);
    }
    printf("PASS: %d reassembly cases (reorder/drop/duplicate/interleave/dst-filter)\n",
           QV_N_REASM);

    /* ── 3. Invariants: a key_ID is always 16 B = exactly 4 fragments ── */
    if (DCF_QKD_KEY_ID_BYTES != DCF_QKD_FRAGS * 4u) fail("key_ID/fragment arithmetic", 0);
    {
        uint8_t kid[DCF_QKD_KEY_ID_BYTES] = {0};
        uint8_t frames[DCF_QKD_FRAGS][DCF_FRAME_SIZE];
        size_t n = 0;
        if (dcf_qkd_packetize(kid, DCF_QKD_MAX_EPOCH + 1u, 0, 1, 1, frames,
                              DCF_QKD_FRAGS, &n))
            fail("epoch above the 14-bit rail must be rejected", 0);
        if (dcf_qkd_packetize(kid, 0, 0, 1, 1, frames, DCF_QKD_FRAGS - 1u, &n))
            fail("insufficient frame room must be rejected", 0);
    }
    printf("PASS: 16 B key_ID = exactly 4 fragments; epoch/room bounds enforced\n");

    /* ── 4. Channel rendezvous anchor: crc16("123456789") == 0x29B1 ── */
    if (dcf_qkd_channel_id("123456789") != 0x29B1) fail("channel_id anchor", 0);
    if (dcf_qkd_channel_id("") != 0xFFFF) fail("channel_id empty=broadcast", 0);
    printf("PASS: channel_id rendezvous anchor holds\n");

    if (failures == 0)
        printf("\nALL QKD VECTORS HOLD — C DCF-QKD L2 is cemented.\n");
    else
        fprintf(stderr, "\n%d FAILURE(S) — C DCF-QKD L2 is NOT cemented.\n", failures);
    return failures != 0;
}
