/* SPDX-License-Identifier: LGPL-3.0-only
 *
 * test_medium_certify.c — C certification for DCF-Medium (the medium codecs).
 *
 * Certifies codec/demod_medium.h against the cross-language golden vectors
 * (codec/medium_vectors.gen.h, generated by python/MCP/gen_medium_vectors.py from the
 * canonical python/MCP/mediumlab_core.py). Passing this == byte/symbol/bit agreement with
 * the Python reference on every family: stream, hex, udp_proto, udp_bare, l2eth,
 * hydra_symbols, afsk_bits.
 *
 * Build: gcc -std=c11 -Wall -Wextra -I codec C_SDK/tests/test_medium_certify.c -lm -o test_mc
 *
 * `punctim certify` (C_SDK/node/punctim.c) compiles this same file with
 * DCF_MEDIUM_CERTIFY_NO_MAIN and calls dcf_medium_certify_run(), so the CLI runs exactly
 * the checks CI runs.
 */
#include <stdio.h>
#include <string.h>
#include "demod_medium.h"
#include "medium_vectors.gen.h"

#define MC_MAX_FRAMES 64

static int mc_failures = 0;
static int mc_quiet = 0;
static char mc_first[160];       /* first failure message since the last family reset */

static void mc_fail(const char *family, const char *name, const char *what) {
    if (!mc_quiet) fprintf(stderr, "FAIL: %s [%s] %s\n", family, name, what);
    if (!mc_failures) snprintf(mc_first, sizeof mc_first, "%s: %s", name, what);
    mc_failures++;
}

static void mc_pass(const char *fmt_family, int n, const char *what) {
    if (!mc_quiet) printf("PASS: %s — %d %s\n", fmt_family, n, what);
}

/* frame collector for the callback-style decoders */
typedef struct { uint8_t f[MC_MAX_FRAMES][17]; size_t n; } mc_sink_t;
static void mc_collect(const uint8_t *frame, void *user) {
    mc_sink_t *s = (mc_sink_t *)user;
    if (s->n < MC_MAX_FRAMES) memcpy(s->f[s->n], frame, 17);
    s->n++;
}

static int mc_frames_eq(const mc_sink_t *s, const uint8_t (*want)[17], int n) {
    if (s->n != (size_t)n) return 0;
    for (int i = 0; i < n; i++)
        if (memcmp(s->f[i], want[i], 17) != 0) return 0;
    return 1;
}

/* ── anchors ──────────────────────────────────────────────────────────────────── */
static void mc_anchors(void) {
    const char *fam = "anchors";
    if (dcf_crc16((const uint8_t *)"123456789", 9) != MED_CRC_123456789) mc_fail(fam, "crc", "CRC(123456789)");
    uint8_t z[15] = {0};
    if (dcf_crc16(z, 15) != MED_CRC_ZERO15) mc_fail(fam, "crc", "CRC(0^15)");
    if (dcf_afsk_crc8((const uint8_t *)"123456789", 9) != MED_AFSK_CRC8_123456789) mc_fail(fam, "crc8", "CRC8(123456789)");
    uint8_t filler[17];
    dcf_l2_filler(filler);
    if (memcmp(filler, MED_L2_FILLER, 17) != 0 || !dcf_medium_gate(filler)) mc_fail(fam, "l2_filler", "filler");
    for (int i = 0; i < 6; i++)
        if (!dcf_medium_gate(MED_BASIS[i])) mc_fail(fam, "basis", "basis frame fails the gate");
    if (MED_FRAME_LEN != DCF_MEDIUM_FRAME_LEN || MED_PROTO_HDR != DCF_MEDIUM_PROTO_HDR ||
        MED_MSG_FRAME != DCF_MEDIUM_MSG_FRAME || MED_SUPER_LEN != DCF_SUPER_LEN ||
        MED_L2_HDR != DCF_L2_HDR || MED_HYDRA_SYNC != DCF_HYDRA_SYNC_WORD ||
        MED_AFSK_SYNC != DCF_AFSK_SYNC)
        mc_fail(fam, "constants", "a medium constant drifted");
    /* the gate rejects a wrong version nibble even with a correct CRC */
    uint8_t v2[17];
    memcpy(v2, MED_BASIS[1], 17);
    v2[1] = (uint8_t)((v2[1] & 0x0Fu) | 0x20u);
    uint16_t c = dcf_crc16(v2, 15);
    v2[15] = (uint8_t)(c >> 8); v2[16] = (uint8_t)c;
    if (dcf_medium_gate(v2)) mc_fail(fam, "gate", "version nibble 2 accepted");
    if (!mc_quiet)
        printf("PASS: anchors — CRC(123456789)=0x29B1, CRC(0^15)=0x4EC3, CRC-8(123456789)=0xA2, "
               "L2 filler, 6 basis frames gate\n");
}

/* ── stream ───────────────────────────────────────────────────────────────────── */
static void mc_stream(void) {
    const char *fam = "stream";
    for (int i = 0; i < MED_N_STREAM; i++) {
        const med_stream_case_t *c = &MED_STREAM_CASES[i];
        mc_sink_t s;
        s.n = 0;
        dcf_stream_result_t r = dcf_stream_scan(c->input, (size_t)c->input_len, mc_collect, &s);
        if (!mc_frames_eq(&s, c->frames, c->n_frames) || r.frames != (size_t)c->n_frames)
            mc_fail(fam, c->name, "decoded frames mismatch");
        if (r.skipped_bytes != (size_t)c->skipped_bytes) mc_fail(fam, c->name, "skipped_bytes mismatch");
        if (r.tail_bytes != (size_t)c->tail_bytes) mc_fail(fam, c->name, "tail_bytes mismatch");
        /* chunk invariance: any chunking yields the same frames + skipped + tail */
        for (int step = 1; step <= 24; step++) {
            dcf_stream_scanner_t sc;
            mc_sink_t s2;
            s2.n = 0;
            dcf_stream_scanner_init(&sc);
            for (int off = 0; off < c->input_len; off += step) {
                int m = c->input_len - off < step ? c->input_len - off : step;
                dcf_stream_feed(&sc, c->input + off, (size_t)m, mc_collect, &s2);
            }
            if (!mc_frames_eq(&s2, c->frames, c->n_frames) || sc.skipped != (uint64_t)c->skipped_bytes ||
                dcf_stream_flush(&sc) != (size_t)c->tail_bytes) {
                mc_fail(fam, c->name, "incremental scanner disagrees with one-shot");
                break;
            }
        }
        /* encode = concatenation; lossless */
        uint8_t enc[6 * 17];
        for (int k = 0; k < c->n_frames; k++) memcpy(enc + 17 * k, c->frames[k], 17);
        mc_sink_t s3;
        s3.n = 0;
        dcf_stream_result_t r3 = dcf_stream_scan(enc, (size_t)(17 * c->n_frames), mc_collect, &s3);
        if (!mc_frames_eq(&s3, c->frames, c->n_frames) || r3.skipped_bytes || r3.tail_bytes)
            mc_fail(fam, c->name, "encode/decode not lossless");
    }
    mc_pass("stream", MED_N_STREAM, "cases: byte-wise resync, skipped/tail counts, chunk-invariant, lossless");
}

/* ── hex ──────────────────────────────────────────────────────────────────────── */
static void mc_hex(void) {
    const char *fam = "hex";
    for (int i = 0; i < MED_N_HEX; i++) {
        const med_hex_case_t *c = &MED_HEX_CASES[i];
        char text[6 * 35 + 1];
        size_t w = 0;
        for (int k = 0; k < c->n_frames; k++) {
            char line[36];
            dcf_hex_encode_line(c->frames[k], line);
            memcpy(text + w, line, 35);
            w += 35;
        }
        text[w] = '\0';
        if (strcmp(text, c->text) != 0) mc_fail(fam, c->name, "encode text mismatch");
        mc_sink_t s;
        s.n = 0;
        size_t bad = 0;
        size_t nf = dcf_hex_decode(c->decode_input, strlen(c->decode_input), mc_collect, &s, &bad);
        if (nf != (size_t)c->n_decoded || !mc_frames_eq(&s, c->decoded, c->n_decoded))
            mc_fail(fam, c->name, "decoded frames mismatch");
        if (bad != (size_t)c->bad_lines) mc_fail(fam, c->name, "bad_lines mismatch");
        /* lossless round trip of the encoded text */
        mc_sink_t s2;
        s2.n = 0;
        dcf_hex_decode(c->text, strlen(c->text), mc_collect, &s2, &bad);
        if (!mc_frames_eq(&s2, c->frames, c->n_frames) || bad) mc_fail(fam, c->name, "round trip");
    }
    mc_pass("hex", MED_N_HEX, "cases: 34 lowercase hex + LF, CRLF/uppercase/comments/blank, bad lines");
}

/* ── udp_proto ────────────────────────────────────────────────────────────────── */
static void mc_proto(void) {
    const char *fam = "udp_proto";
    for (int i = 0; i < MED_N_PROTO; i++) {
        const med_proto_case_t *c = &MED_PROTO_CASES[i];
        uint8_t dg[128];
        size_t n = dcf_medium_proto_encode(c->type, c->seq, c->ts, c->payload,
                                           (uint32_t)c->payload_len, dg, sizeof dg);
        if (n != (size_t)c->datagram_len || memcmp(dg, c->datagram, n) != 0)
            mc_fail(fam, c->name, "encode bytes mismatch");
        uint8_t t; uint32_t seq, plen; uint64_t ts; const uint8_t *p;
        if (!dcf_medium_proto_decode(c->datagram, (size_t)c->datagram_len, &t, &seq, &ts, &p, &plen) ||
            t != c->type || seq != c->seq || ts != c->ts || plen != (uint32_t)c->payload_len ||
            memcmp(p, c->payload, plen) != 0)
            mc_fail(fam, c->name, "decode fields mismatch");
        uint8_t f[17];
        int acc = dcf_proto_frame_decode(c->datagram, (size_t)c->datagram_len, f) ? 1 : 0;
        if (acc != c->accept_as_frame) mc_fail(fam, c->name, "accept_as_frame mismatch");
        if (acc) {
            if (memcmp(f, c->payload, 17) != 0) mc_fail(fam, c->name, "carried frame mismatch");
            uint8_t d34[34];
            if (dcf_proto_frame_encode(c->payload, c->seq, c->ts, d34) != 34 ||
                memcmp(d34, c->datagram, 34) != 0)
                mc_fail(fam, c->name, "proto_frame_encode mismatch");
        }
        /* guards: short header, payload overrun */
        if (c->datagram_len >= 1 &&
            dcf_medium_proto_decode(c->datagram, (size_t)c->datagram_len - 1, &t, &seq, &ts, &p, &plen))
            mc_fail(fam, c->name, "truncated datagram accepted");
    }
    uint8_t shorthdr[16] = {0};
    uint8_t t; uint32_t seq, plen; uint64_t ts; const uint8_t *p;
    if (dcf_medium_proto_decode(shorthdr, 16, &t, &seq, &ts, &p, &plen)) mc_fail(fam, "guard", "16-byte header accepted");
    mc_pass("udp_proto", MED_N_PROTO, "cases: >BIQI envelope, FRAME=12 34-byte datagram, header guards");
}

/* ── udp_bare ─────────────────────────────────────────────────────────────────── */
typedef struct { uint8_t d[16][32]; size_t len[16]; size_t n; } mc_dgrams_t;
static void mc_collect_dgram(const uint8_t *dg, size_t len, void *user) {
    mc_dgrams_t *s = (mc_dgrams_t *)user;
    if (s->n < 16) { memcpy(s->d[s->n], dg, len); s->len[s->n] = len; }
    s->n++;
}

static void mc_bare(void) {
    const char *fam = "udp_bare";
    for (int i = 0; i < MED_N_BARE; i++) {
        const med_bare_case_t *c = &MED_BARE_CASES[i];
        mc_dgrams_t s;
        s.n = 0;
        size_t nd = dcf_bare_pack_pairs(c->frames, (size_t)c->n_frames, true, mc_collect_dgram, &s);
        if (nd != (size_t)c->n_datagrams || s.n != nd) { mc_fail(fam, c->name, "datagram count"); continue; }
        mc_sink_t got;
        got.n = 0;
        for (size_t k = 0; k < nd; k++) {
            if (s.len[k] != (size_t)c->datagram_len[k] || memcmp(s.d[k], c->datagrams[k], s.len[k]) != 0)
                mc_fail(fam, c->name, "datagram bytes mismatch");
            uint8_t out[2][17];
            int m = dcf_bare_unpack(c->datagrams[k], (size_t)c->datagram_len[k], out);
            for (int j = 0; j < m; j++) mc_collect(out[j], &got);
        }
        if (!mc_frames_eq(&got, c->frames, c->n_frames)) mc_fail(fam, c->name, "unpack not lossless");
        /* pair = false: every frame raw */
        mc_dgrams_t r;
        r.n = 0;
        if (dcf_bare_pack_pairs(c->frames, (size_t)c->n_frames, false, mc_collect_dgram, &r) != (size_t)c->n_frames)
            mc_fail(fam, c->name, "pair=0 count");
    }
    uint8_t junk[20] = {0}, out[2][17];
    if (dcf_bare_unpack(junk, 20, out) != 0) mc_fail(fam, "junk", "20-byte datagram accepted");
    mc_pass("udp_bare", MED_N_BARE, "cases: pairs -> 32-B SuperPack, lone frame raw, lossless");
}

/* ── l2eth ────────────────────────────────────────────────────────────────────── */
static void mc_l2(void) {
    const char *fam = "l2eth";
    for (int i = 0; i < MED_N_L2; i++) {
        const med_l2_case_t *c = &MED_L2_CASES[i];
        uint8_t pl[130];
        size_t n = 0;
        if (!dcf_l2_batch(c->frames, (size_t)c->n_frames, pl, sizeof pl, &n) ||
            n != (size_t)c->payload_len || memcmp(pl, c->payload, n) != 0)
            mc_fail(fam, c->name, "batch bytes mismatch");
        uint8_t fr[8][17];
        size_t got = 0;
        if (!dcf_l2_unbatch(c->payload, (size_t)c->payload_len, fr, 8, &got) || got != (size_t)c->n_frames)
            mc_fail(fam, c->name, "unbatch count");
        else
            for (size_t k = 0; k < got; k++)
                if (memcmp(fr[k], c->frames[k], 17) != 0) mc_fail(fam, c->name, "unbatch frame mismatch");
        if (dcf_l2_unbatch(c->payload, (size_t)c->payload_len - 1, fr, 8, &got))
            mc_fail(fam, c->name, "truncated batch accepted");
    }
    if (dcf_l2_capacity(1500) != 92) mc_fail(fam, "capacity", "l2_capacity(1500) != 92");
    mc_pass("l2eth", MED_N_L2, "cases: [n u16][SuperPack*ceil(n/2)], zero-DATA filler, truncation rejected");
}

/* ── hydra_symbols ────────────────────────────────────────────────────────────── */
static void mc_hydra(void) {
    const char *fam = "hydra_symbols";
    for (int i = 0; i < 2; i++) {
        const med_hydra_profile_t *v = &MED_HYDRA_PROFILES[i];
        dcf_hydra_profile_t p;
        if (dcf_hydra_profile_named(&p, v->name) != 0) { mc_fail(fam, v->name, "unknown profile"); continue; }
        if (!(p.sample_rate <= v->sample_rate && p.sample_rate >= v->sample_rate) ||
            !(p.baud <= v->baud && p.baud >= v->baud) || p.n_tones != v->n_tones ||
            !(p.base_freq <= v->base_freq && p.base_freq >= v->base_freq) ||
            !(p.tone_spacing <= v->tone_spacing && p.tone_spacing >= v->tone_spacing) ||
            p.preamble_syms != v->preamble_syms || p.sync_word != v->sync_word)
            mc_fail(fam, v->name, "profile user fields drifted");
    }
    int corrected = 0;
    for (int i = 0; i < MED_N_HYDRA; i++) {
        const med_hydra_case_t *c = &MED_HYDRA_CASES[i];
        dcf_hydra_profile_t p;
        if (dcf_hydra_profile_named(&p, c->profile) != 0) { mc_fail(fam, c->name, "unknown profile"); continue; }
        p.fec_mode = c->fec;
        p.interleave = c->interleave;
        p.n_tones = c->n_tones;
        if (dcf_hydra_profile_init(&p) != 0) { mc_fail(fam, c->name, "profile_init rejected"); continue; }
        if (p.coded_bits != (size_t)c->coded_bits || p.interleave_stride != (size_t)c->interleave_stride ||
            p.total_syms != (size_t)c->total_syms)
            mc_fail(fam, c->name, "derived profile fields mismatch");
        uint8_t syms[1024];
        char str[1025];
        size_t n = 0;
        if (dcf_hydra_symbols_encode(&p, c->frame, syms, sizeof syms, &n) != 0) {
            mc_fail(fam, c->name, "encode failed");
            continue;
        }
        dcf_hydra_symbols_to_str(syms, n, str);
        if (n != (size_t)c->total_syms || strcmp(str, c->symbols) != 0)
            mc_fail(fam, c->name, "symbol stream mismatch");
        uint8_t vs[1024], f[17];
        size_t vn = dcf_hydra_symbols_from_str(c->symbols, vs, sizeof vs);
        if (vn == (size_t)-1 || dcf_hydra_symbols_decode(&p, vs, vn, f) != 0 || memcmp(f, c->frame, 17) != 0)
            mc_fail(fam, c->name, "decode(vector) != frame");
        /* the decoder rejects a corrupted sync word */
        vs[p.preamble_syms] ^= 1u;
        if (dcf_hydra_symbols_decode(&p, vs, vn, f) == 0) mc_fail(fam, c->name, "bad sync accepted");
        vs[p.preamble_syms] ^= 1u;
        /* hard Viterbi corrects a flipped data symbol (binary conv: one coded-bit error) */
        if (c->fec == DCF_HYDRA_FEC_CONV && c->n_tones == 2) {
            size_t k = (size_t)p.preamble_syms + p.sync_syms + p.data_syms / 2u;
            vs[k] ^= 1u;
            if (dcf_hydra_symbols_decode(&p, vs, vn, f) != 0 || memcmp(f, c->frame, 17) != 0)
                mc_fail(fam, c->name, "conv did not correct a single symbol error");
            else
                corrected++;
        }
        /* uncoded: a flipped data symbol must fail the CRC */
        if (c->fec == DCF_HYDRA_FEC_NONE && c->n_tones == 2) {
            size_t k = (size_t)p.preamble_syms + p.sync_syms + 3u;
            vs[k] ^= 1u;
            if (dcf_hydra_symbols_decode(&p, vs, vn, f) == 0) mc_fail(fam, c->name, "corrupt uncoded frame accepted");
        }
    }
    uint8_t bits[152], coded[316], back[152];
    dcf_hydra_bytes_to_bits(MED_BASIS[1], 17, bits);
    memset(bits + 136, 0, 16);
    if (dcf_hydra_conv_encode(bits, 152, coded) != 316 || dcf_hydra_conv_decode_hard(coded, 316, back) != 152 ||
        memcmp(back, bits, 152) != 0)
        mc_fail(fam, "conv", "conv_decode_hard(conv_encode(x)) != x");
    if (!mc_quiet)
        printf("PASS: hydra_symbols — %d cases: coded 152/456/316, stride 13/23/19, symbol streams "
               "byte-identical, decode(vector)=frame (%d conv single-error corrections)\n",
               MED_N_HYDRA, corrected);
}

/* ── afsk_bits ────────────────────────────────────────────────────────────────── */
static void mc_afsk(void) {
    const char *fam = "afsk_bits";
    for (int i = 0; i < 3; i++) {
        const med_afsk_profile_t *v = &MED_AFSK_PROFILES[i];
        const dcf_afsk_profile_t *p = dcf_afsk_profile(v->name);
        if (!p || p->baud != v->baud || p->preamble_bits != v->preamble_bits ||
            !(p->mark <= v->mark && p->mark >= v->mark) || !(p->space <= v->space && p->space >= v->space))
            mc_fail(fam, v->name, "profile drifted");
    }
    for (int i = 0; i < MED_N_AFSK; i++) {
        const med_afsk_case_t *c = &MED_AFSK_CASES[i];
        const dcf_afsk_profile_t *p = dcf_afsk_profile(c->profile);
        if (!p) { mc_fail(fam, c->name, "unknown profile"); continue; }
        uint8_t bits[DCF_AFSK_MAX_BITS];
        char str[DCF_AFSK_MAX_BITS + 1];
        size_t n = dcf_afsk_bits_encode(c->frame, p->preamble_bits, c->fec != 0, bits, sizeof bits);
        dcf_afsk_bits_to_str(bits, n, str);
        if (n != (size_t)c->n_bits || strcmp(str, c->bits) != 0) mc_fail(fam, c->name, "bit stream mismatch");
        uint8_t vb[DCF_AFSK_MAX_BITS], f[17];
        size_t vn = dcf_afsk_bits_from_str(c->bits, vb, sizeof vb);
        if (vn == (size_t)-1 || dcf_afsk_bits_decode(vb, vn, c->fec != 0, f) != 0 || memcmp(f, c->frame, 17) != 0)
            mc_fail(fam, c->name, "decode(vector) != frame");
        /* RS corrects a flipped payload byte; crc8 detects it */
        size_t k = (size_t)p->preamble_bits + 8u + 8u * 5u;
        for (size_t b = 0; b < 8; b++) vb[k + b] ^= 1u;
        int rc = dcf_afsk_bits_decode(vb, vn, c->fec != 0, f);
        if (c->fec ? (rc != 0 || memcmp(f, c->frame, 17) != 0) : (rc == 0))
            mc_fail(fam, c->name, c->fec ? "RS did not correct a byte error" : "crc8 missed a byte error");
    }
    mc_pass("afsk_bits", MED_N_AFSK, "cases: preamble + 0x7E + frame+crc8 | RS16 + postamble, decode(vector)=frame");
}

/* ── driver ───────────────────────────────────────────────────────────────────── */
static const struct { const char *name; void (*run)(void); int n; } MC_FAMILIES[] = {
    {"anchors", mc_anchors, 6},              {"stream", mc_stream, MED_N_STREAM},
    {"hex", mc_hex, MED_N_HEX},              {"udp_proto", mc_proto, MED_N_PROTO},
    {"udp_bare", mc_bare, MED_N_BARE},       {"l2eth", mc_l2, MED_N_L2},
    {"hydra_symbols", mc_hydra, MED_N_HYDRA}, {"afsk_bits", mc_afsk, MED_N_AFSK},
};
#define MC_N_FAMILIES ((int)(sizeof MC_FAMILIES / sizeof MC_FAMILIES[0]))

#ifdef DCF_MEDIUM_CERTIFY_NO_MAIN
/* The CLI face (`punctim certify`): run ONE family silently. Returns its failure count;
 * *ncases = its case count and msg = the first failure. -1 for an unknown family. */
static int dcf_medium_certify_family(const char *name, int *ncases, char *msg, size_t msglen) {
    for (int i = 0; i < MC_N_FAMILIES; i++) {
        if (strcmp(MC_FAMILIES[i].name, name) != 0) continue;
        mc_quiet = 1;
        mc_failures = 0;
        mc_first[0] = '\0';
        MC_FAMILIES[i].run();
        *ncases = MC_FAMILIES[i].n;
        snprintf(msg, msglen, "%s", mc_first);
        return mc_failures;
    }
    return -1;
}
#else
int main(void) {
    for (int i = 0; i < MC_N_FAMILIES; i++) MC_FAMILIES[i].run();
    if (mc_failures) {
        fprintf(stderr, "\n%d FAILURE(S)\n", mc_failures);
        return 1;
    }
    printf("\nALL MEDIUM VECTORS HOLD — C DCF-Medium is cemented.\n");
    return 0;
}
#endif
